config/routes.rb
Openfinance::Application.routes.draw do
  get "transfer/index"













resources :section do
  resources :field do
  end
end


  root :to => 'transfer#index'
  match "/filter" => 'transfer#filter', :as => ''
  match "/section/:id" => 'section#show' ,:as => :section
  match "/section/:id/field/:id" => 'field#show', :as => :field
  match "/section/:id/field/:id/get_transfers" => 'field#get_transfers'
  match "/section/:id/field/:id/program:id" => 'program#show', :as => :program
end

app/models/field.rb
class Field < ActiveRecord::Base
	Field.pluralize_table_names = false
	self.table_name = 'transfers'
	belongs_to :section


	  def to_param
	  	field_id
	  end
end

app/models/program.rb
class Program < ActiveRecord::Base
	Program.pluralize_table_names = false
	Program.set_table_name("transfers")
	belongs_to :field


	  def to_param
	  	program_id
	  end
end

app/models/section.rb
class Section < ActiveRecord::Base
	Section.pluralize_table_names = false
	self.table_name = 'transfers'
	has_many :field
	belongs_to :transer


	  def to_param
	  	section_id
	  end
end

app/models/transfer.rb
class Transfer < ActiveRecord::Base
	has_many :section
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  	#method integreates between data from DB and from Open Budget and creates JSON for bubble chart
	def createJSON(level)
	#groups hash defines devision to colour groups
	groups = [	{:name => "very_high", :upper => 10000, :lower => 0.15},
				{:name => "high", :upper => 0.15, :lower => 0.05},
				{:name => "medium", :upper => 0.05, :lower => -0.05},   	
			   	{:name => "low", :upper => -0.05, :lower => -0.15},
			   	{:name => "very_low", :upper => -0.15, :lower => -1000}
			 ]

			 puts @obudget
			 puts @transfers

		#array that holds the final bubble data
		@section_array = []
		#array that holds section names from auto complete search bar
		@auto_complete = []

		@transfers.each_with_index do |section,index_section|
			#section_string = creating the section string for lookup in "Open Budget"
			section_string = getSectionString(section,level)
			puts section_string
			#check if section can't be found in open budget 
			#or if the section has a 0 budget	
			unless @obudget.find {|s| s["budget_id"] ==  section_string}.nil? ||  @obudget.find {|s| s["budget_id"] ==  section_string}["net_amount_allocated"] == 0
				puts "i found it"
				budget = @obudget.find {|s| s["budget_id"] == section_string}["net_amount_allocated"]   
				percent = section.net / budget
				#loop over group hash to find the correct group (low,medim,high)						
				groups.each_with_index do |group,index|
					flag = false
					if percent.between?(group[:lower],group[:upper])
						#once we found the group we create the bubble
						#budget size * 1000 since it is saved as /1000 in open budget
						bubble = {:id => index_section, :total_amount => budget*1000, 
								  :section_id => section.level_id,
						          :group => group[:name],
						          :value => budget*1000,
						          :percent => percent.round(3)*100,
						          :p_f => group[:p_from], :p_t => group[:p_to],
						          :section_name => section.level_name,
						          :start_year => 2009
						   		}
						@auto_complete.push({:label => section.level_name, :value => section.level_name, :id => index_section, :budget => bubble[:value], :percent =>bubble[:percent]})
						@section_array.push(bubble)
						flag = true
					end
					break if flag
				end	
			end
		end
	end

	def getSectionString(section,level)
		case level
		when 'section'
			return section.level_id.length > 1 ? "00" + section.level_id : "000" + section.level_id
		when 'field'
			return "00" + params[:id] + section.level_id
		when 'program'
			return "00" + params[:section_id] + params[:id] + section.level_id
		end
	end

end

app/controllers/field_controller.rb
class FieldController < ApplicationController
	include ActionView::Helpers::NumberHelper
	def show
		require 'open-uri'
		require 'json'
		#variable that contains the query from transfers table
		@transfers =  Field.select("section_name,field_name,program_id as level_id,program_name as level_name,sum(net) as net").where("section_id = ? AND field_id = ?", params[:section_id],params[:id]).group("field_name,field_id,program_id,program_name").order("program_id ASC")
		#variable that contains information from 'open budget'
		@obudget = JSON.parse(open("http://budget.yeda.us/00" + params[:section_id] + params[:id] + "?year=2011&depth=1").read)
		@breadcrumbs = {
				:section_id => params[:section_id],
			  	:section_name => @transfers[0].section_name,
			  	:field_id => params[:id],
			  	:field_name => @transfers[0].field_name,
			  	:program_id => nil
			 			} 
		createJSON('program')

		@json = @section_array.to_json.html_safe 
		@path = "/program/"
		@transfers = []
		@auto_complete = @auto_complete.to_json.html_safe 
	end		

	def get_transfers
		transfers = Field.select("section_name,field_name,program_name,pniya_id,request_desc,net").where("section_id = ? AND field_id = ? AND program_id = ?", params[:section_id],params[:id],params[:program_id]).order("pniya_id")
		logger.info(params)
		logger.info(transfers.size)
		@json = transfers.to_json
		transfers.each do |t|
		logger.info(t.program_name)
		end
		respond_to do |format|
   			 format.json { render json: @json }
		end
	end		
end

app/controllers/program_controller.rb
class ProgramController < ApplicationController
	def show
		require 'open-uri'
		require 'json'
		@json = JSON.parse(open("http://budget.yeda.us/00?year=2005&depth=3").read)
		@breadcrumbs = {:section_id => nil}  
	end
end

app/controllers/section_controller.rb
class SectionController < ApplicationController
	include ActionView::Helpers::NumberHelper
	def show
		require 'open-uri'
		require 'json'
		#variable that contains the query from transfers table
		@transfers = Section.select("section_name,section_id,field_id as level_id,field_name as level_name,sum(net) as net").where("section_id = ?", params[:id]).group("field_id").order("field_id ASC")
		#variable that contains information from 'open budget'
		@obudget = JSON.parse(open("http://budget.yeda.us/00" + params[:id] +"?year=2011&depth=1").read)

		@breadcrumbs = {:section_id => params[:id],
					  :section_name => @transfers[0].section_name,
					  :field_id => nil
					 }  

		createJSON('field')

		@json = @section_array.to_json.html_safe 
		@path = "/field/"
		@auto_complete = @auto_complete.to_json.html_safe
	end	

end

app/controllers/transfer_controller.rb
class TransferController < ApplicationController
	include ActionView::Helpers::NumberHelper
	def index
		require 'open-uri'
		require 'json'

		#just for now!
		if session[:year].nil?
			session[:year] = "2011"
		end

		#variable that contains the query from transfers table
		@transfers = Transfer.select("section_id as level_id,section_name as level_name,sum(net) as net").where("year = ?",session[:year]).group("section_id,section_name").order("section_id ASC")
		#variable that contains information from 'open budget'
		@obudget = JSON.parse(open("http://budget.yeda.us/00?year="+ session[:year]+ "&depth=1").read)
		@breadcrumbs = {:section_id => nil}  

		
		createJSON('section')

		@auto_complete = @auto_complete.to_json.html_safe
		@json = @section_array.to_json.html_safe

		@path = "/section/"
	end

	def filter
		session[:year] = params[:year]
		redirect_to :root
	end
end


app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  			Transfer.where(:section_id => "section_id").destroy_all

  	@transfers = Transfer.all
  	require 'open-uri'
	require 'json'
	#@result = JSON.parse(open("http://budget.yeda.us/00?year=2011&depth=1").read)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/field_helper.rb
module FieldHelper
end

app/helpers/program_helper.rb
module ProgramHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/transfer_helper.rb
module TransferHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/field/_bar_js.html.erb
<script src="http://code.highcharts.com/highcharts.js"></script>
<script src="http://code.highcharts.com/modules/exporting.js"></script>
 <script type="text/javascript" charset="utf-8">
$(function () {
    var chart;
    $(document).ready(function() {
        chart = new Highcharts.Chart({
            chart: {
                renderTo: 'container',
                type: 'column'
            },
            title: {
                text: "סכום העברות לפי תכנית פעולה"
            },
            xAxis: {
                categories:  <%= @categories %>
            },
                plotOptions: {
        series: {
            shadow:false,
            cursor:'pointer',
            point: {
                events: {
                    click: function() {
                        //location.href = this.options.url;
                        window.open(this.options.url);
                    }
                }
            }
        }
    },
            tooltip: {
                formatter: function() {
                    return ''+
                        this.series.name +': '+ this.y +'';
                }
            },
            credits: {
                enabled: false
            },
            series: <%= @series %>
        });
    });   
});
 </script>

app/views/field/_bar_js_test.html.erb
<script src="http://code.highcharts.com/highcharts.js"></script>
<script src="http://code.highcharts.com/modules/exporting.js"></script>
 <script type="text/javascript" charset="utf-8">
$(function () {
    var chart = new Highcharts.Chart({
        chart: {
            renderTo: 'container',
            type: 'column'
        },
        xAxis: {
            categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
        },
        
        plotOptions: {
            series: {
                cursor: 'pointer',
                point: {
                    events: {
                        click: function() {
                            alert ('Category: '+ this.category +', value: '+ this.y);
                        }
                    }
                }
            }
        },
        
        series: [{
            data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4]        
        }]
    });
});
</script>

app/views/field/show.html.erb
<div id="vis"></div>
<%= render :partial => 'shared/bubbles_js' %>


<table class="table table-striped" id="transfer_table">
  <caption>טבלת כלל ההעברות בתכנית פעולה זו</caption>
   <thead>
    <tr>
      <th>מספר פנייה</th>
      <th>תיאור הבקשה</th>
      <th>סכום נטו</th>
    </tr>
   </thead>
   <tbody>
   </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>פותחים את ועדת הכספים</title>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js" %>
  <%= javascript_include_tag "http://d3js.org/d3.v3.min.js" %>
  <%= javascript_include_tag "http://code.jquery.com/ui/1.10.2/jquery-ui.js" %>
  <%= javascript_include_tag "https://www.google.com/jsapi" %>
  <%= stylesheet_link_tag "http://code.jquery.com/ui/1.10.2/themes/smoothness/jquery-ui.css" %>

  <!--%= javascript_include_tag "application" %-->
  <%= csrf_meta_tags %>
</head>
<body>

<div class = "head">
  <div class="navbar">
  	<div class="navbar-inner">
  	<a class="brand" href="#">ועדת הכספים הפתוחה</a>
  	<ul class="nav">
  		<li><a href="#">על ועדת הכספים</a></li>
  		<li><a href="#">צרו קשר</a></li>
      <li><%= text_field_tag 'query', nil, :placeholder => 'חפש שם סעיף' %></li>
      <li>
        <select name="vbitratecontrol0" id="year" onchange="comboChange()">;
          <option value="2011">2011</option>
          <option value="2010">2010</option>
          <option value="2009">2009</option>
          <option value="2008">2008</option>
          <option value="2007">2007</option>
          <option value="2006">2006</option>
          <option value="2005">2005</option>
      </select>
      </li>
  	</ul>
  	</div>
  </div>

  <ul class="breadcrumb" align="right">
    <li><a href="/">התקציב</a> <span class="divider">/</span></li>
    <% unless @breadcrumbs[:section_id].nil? %>
    	<li><%= link_to @breadcrumbs[:section_name], section_path(@breadcrumbs[:section_id]) %>
    	<span class="divider">/</span></li>
    	<% unless @breadcrumbs[:field_id].nil? %>
    		<li><%= link_to @breadcrumbs[:field_name], section_field_path(@breadcrumbs[:section_id],@breadcrumbs[:field_id]) %>
    		<span class="divider">/</span></li>
    		<% unless @breadcrumbs[:program_id].nil? %>
    			<li><%= link_to @breadcrumbs[:program_name], section_field_program_path(@breadcrumbs[:section_id],@breadcrumbs[:field_id],@breadcrumbs[:program_id]) %>
    			<span class="divider">/</span></li>
    		<% end %>
    	<% end %>
    <% end %>
  </ul>
</div>

<div class="container-fluid">
  <div class="row-fluid">
    <div class="span8" id="right">
      <div class="row-fluid">
        <div class="span4">
           <div class = "well well-large">
          <%= image_tag 'legend.png' %>
        </div>
        </div>
        <div class="span7">
          <h1 class="bubble_title">תקציב המדינה</h1>
          <%= yield %>
      </div>
    </div>
    </div>
    <div class="span3" id="left">
      <div id="chart_div"></div>
  </div>
  </div>
</div>


<div id="wrapper">
<!--div id="footer_container_1">
    <div id="footer_1">תחתית האתר</div>
</div-->
</div>

</body>
</html>

app/views/program/show.html.erb
<div id="transfer_table">
<table class="table table-striped">
  <caption>טבלת כלל ההעברות בתכנית פעולה זו</caption>
   <thead>
    <tr>
      <th>שם</th>
      <th>קוד</th>
    </tr>
   </thead>
   <tbody>
    <% @json.each do |budget| %>
    <tr>
      <td><%= budget["title"] %></td>
      <td><%= budget["budget_id"] %></td>
    </tr>
    <% end %>
   </tbody>
</table>
<div>

app/views/section/_bar_js.html.erb
<script src="http://code.highcharts.com/highcharts.js"></script>
<script src="http://code.highcharts.com/modules/exporting.js"></script>
 <script type="text/javascript" charset="utf-8">
$(function () {
    var chart;
    $(document).ready(function() {
        chart = new Highcharts.Chart({
            chart: {
                renderTo: 'container',
                type: 'column'
            },
            title: {
                text: "סכום העברות לפי תחום פעולה"
            },
            xAxis: {
                categories:  <%= @categories %>
            },
            tooltip: {
                formatter: function() {
                    return ''+
                        this.series.name +': '+ this.y +'';
                }
            },
            credits: {
                enabled: false
            },
            series: <%= @series %>
        });
    });
    
});
 </script>

app/views/section/_bar_js_test.html.erb
<script src="http://code.highcharts.com/highcharts.js"></script>
<script src="http://code.highcharts.com/modules/exporting.js"></script>
 <script type="text/javascript" charset="utf-8">
$(function () {
    var chart = new Highcharts.Chart({
        chart: {
            renderTo: 'container',
            type: 'column'
        },
        xAxis: {
            categories: <%= @categories %>
        },
        
        plotOptions: {
            series: {
                cursor: 'pointer',
                point: {
                    events: {
                        click: function() {
                            window.location = "/section/field/" + this.y;
                        }
                    }
                }
            }
        },
        
        series: <%= @series %>
    });
});
</script>

app/views/section/show.html.erb
<div id="vis"></div>
<%= render :partial => 'shared/bubbles_js' %>

app/views/shared/_autocomplete_js.html.erb
  <script>
  $(function() {
    var availableNames = <%= @auto_complete %>;
    $( "#query" ).autocomplete({
      source: availableNames,

      select: function( event, ui ) {
        debugger;
        alert(ui.item.id)
      }
    });
  });
  </script>

app/views/shared/_bar_js.html.erb

<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">
  google.load("visualization", "1", {packages:["corechart"]});
  google.setOnLoadCallback(drawChart);
  function drawChart() {

    sections = <%= @json %>;
    sections.sort(function(a, b){
     return b.percent-a.percent
    });

    len = sections.length;
    winners = sections.slice(0,5);
    losers = sections.slice(len-5, len+1);

    var data = new google.visualization.DataTable();
    data.addColumn('string', 'Month'); // Implicit domain label col.
    data.addColumn('number', 'Sales'); // Implicit series 1 data col.
    data.addColumn({type:'string', role:'tooltip'});
    data.addColumn('number', 'Expenses');
    data.addColumn({type:'string', role:'tooltip'});

    for (var i = 0; i < 5; i++) {
      data.addRows([[String(i),Math.round(winners[i].percent *100)/100,'a',Math.round(losers[4-i].percent * 100)/100,'b']]);
    };

    var options = {
      title: 'Company Performance',
      vAxis: {title: 'Year',  titleTextStyle: {color: 'red'}}
    };


    var chart = new google.visualization.BarChart(document.getElementById('chart_div'));
    chart.draw(data, options);
    google.visualization.events.addListener(chart, 'onmouseover', function(){});
}
</script>

app/views/transfer/_bubbles_js.html.erb
 <script type="text/javascript">
  (function () {
  var BubbleChart, root,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  BubbleChart = (function() {

    function BubbleChart(data) {
      this.hide_details = __bind(this.hide_details, this);

      this.show_details = __bind(this.show_details, this);

      this.hide_years = __bind(this.hide_years, this);
      debugger;
      this.display_years = __bind(this.display_years, this);

      this.move_towards_year = __bind(this.move_towards_year, this);

      this.display_by_year = __bind(this.display_by_year, this);

      this.move_towards_center = __bind(this.move_towards_center, this);

      this.display_group_all = __bind(this.display_group_all, this);

      this.start = __bind(this.start, this);

      this.create_vis = __bind(this.create_vis, this);

      this.create_nodes = __bind(this.create_nodes, this);

      var max_amount;
      this.data = data;
      this.width = 940;
      this.height = 600;
      this.tooltip = CustomTooltip("gates_tooltip", 240);
      this.center = {
        x: this.width / 2,
        y: this.height / 2
      };
      this.year_centers = {
        "2008": {
          x: this.width / 3,
          y: this.height / 2
        },
        "2009": {
          x: this.width / 2,
          y: this.height / 2
        },
        "2010": {
          x: 2 * this.width / 3,
          y: this.height / 2
        }
      };
      this.layout_gravity = -0.01;
      this.damper = 0.1;
      this.vis = null;
      this.nodes = [];
      this.force = null;
      this.circles = null;
      this.fill_color = d3.scale.ordinal().domain(["low", "medium", "high"]).range(["#d84b2a", "#beccae", "#7aa25c"]);
      max_amount = d3.max(this.data, function(d) {
        return parseInt(d.total_amount);
      });
      this.radius_scale = d3.scale.pow().exponent(0.5).domain([0, max_amount]).range([2, 85]);
      this.create_nodes();
      this.create_vis();
    }

    BubbleChart.prototype.create_nodes = function() {
      var _this = this;
      this.data.forEach(function(d) {
        var node;
        node = {
          id: d.id,
          radius: _this.radius_scale(parseInt(d.total_amount)),
          value: d.value,
          name: d.grant_title,
          org: d.organization,
          group: d.group,
          year: d.start_year,
          x: Math.random() * 900,
          y: (Math.random() * (d.p_t-d.p_f)+d.p_f) * 800
        };
        return _this.nodes.push(node);
      });
      return this.nodes.sort(function(a, b) {
        return b.value - a.value;
      });
    };

    BubbleChart.prototype.create_vis = function() {
      var that,
        _this = this;
      this.vis = d3.select("#vis").append("svg").attr("width", this.width).attr("height", this.height).attr("id", "svg_vis");
      this.circles = this.vis.selectAll("circle").data(this.nodes, function(d) {
        return d.id;
      });
      that = this;
      this.circles.enter().append("circle").attr("r", 0).attr("fill", function(d) {
        return _this.fill_color(d.group);
      }).attr("stroke-width", 2).attr("stroke", function(d) {
        return d3.rgb(_this.fill_color(d.group)).darker();
      }).attr("id", function(d) {
        return "bubble_" + d.id;
      }).on("mouseover", function(d, i) {
        return that.show_details(d, i, this);
      }).on("mouseout", function(d, i) {
        return that.hide_details(d, i, this);
      });
      return this.circles.transition().duration(2000).attr("r", function(d) {
        return d.radius;
      });
    };

    BubbleChart.prototype.charge = function(d) {
      return -Math.pow(d.radius, 2.0) / 8;
    };

    BubbleChart.prototype.start = function() {
      return this.force = d3.layout.force().nodes(this.nodes).size([this.width, this.height]);
    };

    BubbleChart.prototype.display_group_all = function() {
      var _this = this;
      this.force.gravity(this.layout_gravity).charge(this.charge).friction(0.9).on("tick", function(e) {
        return _this.circles.each(_this.move_towards_center(e.alpha)).attr("cx", function(d) {
          return d.x;
        }).attr("cy", function(d) {
          return d.y;
        });
      });
      this.force.start();
      return this.hide_years();
    };

    BubbleChart.prototype.move_towards_center = function(alpha) {
      var _this = this;
      return function(d) {
        d.x = d.x + (_this.center.x - d.x) * (_this.damper + 0.02) * alpha;
        return d.y = d.y + (_this.center.y - d.y) * (_this.damper + 0.02) * alpha;
      };
    };

    BubbleChart.prototype.display_by_year = function() {
      var _this = this;
      this.force.gravity(this.layout_gravity).charge(this.charge).friction(0.9).on("tick", function(e) {
        return _this.circles.each(_this.move_towards_year(e.alpha)).attr("cx", function(d) {
          return d.x;
        }).attr("cy", function(d) {
          return d.y;
        });
      });
      this.force.start();
      return this.display_years();
    };

    BubbleChart.prototype.move_towards_year = function(alpha) {
      var _this = this;
      return function(d) {
        var target;
        target = _this.year_centers[d.year];
        d.x = d.x + (target.x - d.x) * (_this.damper + 0.02) * alpha * 1.1;
        return d.y = d.y + (target.y - d.y) * (_this.damper + 0.02) * alpha * 1.1;
      };
    };

    BubbleChart.prototype.display_years = function() {
      var years, years_data, years_x,
        _this = this;
      years_x = {
        "2008": 160,
        "2009": this.width / 2,
        "2010": this.width - 160
      };
      years_data = d3.keys(years_x);
      years = this.vis.selectAll(".years").data(years_data);
      return years.enter().append("text").attr("class", "years").attr("x", function(d) {
        return years_x[d];
      }).attr("y", 40).attr("text-anchor", "middle").text(function(d) {
        return d;
      });
    };

    BubbleChart.prototype.hide_years = function() {
      var years;
      return years = this.vis.selectAll(".years").remove();
    };

    BubbleChart.prototype.show_details = function(data, i, element) {
      var content;
      d3.select(element).attr("stroke", "black");
      content = "<span class=\"title\"> " + data.name + "</span><br/>";
      content += "<span class=\"budget\">" + data.value + "₪</span>";
      content += "<span class=\"percent\">" + data.year + "</span>";
      return this.tooltip.showTooltip(content, d3.event);
    };

    BubbleChart.prototype.hide_details = function(data, i, element) {
      var _this = this;
      d3.select(element).attr("stroke", function(d) {
        return d3.rgb(_this.fill_color(d.group)).darker();
      });
      return this.tooltip.hideTooltip();
    };

    return BubbleChart;

  })();

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  $(function() {
    var chart, data_ex, render_vis,
      _this = this;
    chart = null;
    render_vis = function(csv) {
      chart = new BubbleChart(csv);
      chart.start();
      return root.display_all();
    };
    root.display_all = function() {
      return chart.display_group_all();
    };
    root.display_year = function() {
      return chart.display_by_year();
    };
    root.toggle_view = function(view_type) {
      if (view_type === 'year') {
        return root.display_year();
      } else {
        return root.display_all();
      }
    };
data_ex = <%= @json %>;
    return render_vis(data_ex);
  });

}).call(this);

function CustomTooltip(tooltipId, width) {
    var tooltipId = tooltipId;
    $("body").append("<div class='tooltip' id='" + tooltipId + "'></div>");

    if (width) {
        $("#" + tooltipId).css("width", width);
    }

    hideTooltip();

    function showTooltip(content, event) {
        $("#" + tooltipId).html(content);
        $("#" + tooltipId).show();

        updatePosition(event);
    }

    function hideTooltip() {
        $("#" + tooltipId).hide();
    }

    function updatePosition(event) {
        var ttid = "#" + tooltipId;
        var xOffset = 20;
        var yOffset = 10;

        var ttw = $(ttid).width();
        var tth = $(ttid).height();
        var wscrY = $(window).scrollTop();
        var wscrX = $(window).scrollLeft();
        var curX = (document.all) ? event.clientX + wscrX : event.pageX;
        var curY = (document.all) ? event.clientY + wscrY : event.pageY;
        var ttleft = ((curX - wscrX + xOffset * 2 + ttw) > $(window).width()) ? curX - ttw - xOffset * 2 : curX + xOffset;
        if (ttleft < wscrX + xOffset) {
            ttleft = wscrX + xOffset;
        }
        var tttop = ((curY - wscrY + yOffset * 2 + tth) > $(window).height()) ? curY - tth - yOffset * 2 : curY + yOffset;
        if (tttop < wscrY + yOffset) {
            tttop = curY + yOffset;
        }
        $(ttid).css('top', tttop + 'px').css('left', ttleft + 'px');
    }

    return {
        showTooltip: showTooltip,
        hideTooltip: hideTooltip,
        updatePosition: updatePosition
    }
}
</script>

app/views/transfer/index.html.erb

<div id="vis"></div>

<%= render :partial => 'shared/bubbles_js' %>




app/views/welcome/index.html.erb
<table>
  <tr>
    <th>section_id</th>
    <th>net</th>
  </tr>

  <% @transfers.each do |transfer| %>
    <tr>
      <td><%= transfer.section_id %></td>
      <td><%= transfer.net %></td>
    </tr>
<% end %>
</table>